
# -*- restclient -*-

#Variables
:port = 8080
:api = http://localhost::port/api/v1

# ======== Test Game Creation End-Point ========
# Create a new game
# Returns join codes for Red, Blue and Spymaster
POST :api/games
